### ISSUE TITLE
Syslog changes since logstash version 2.4.x

### ISSUE THREAD

**Issue by bcecchinato** [logstash-plugins/logstash-input-syslog#32]
Hi there !

I've migrated from logstash 2.4.x to 5.0.1, and found out that the input-syslog plugin doesn't work the same way than before.

Before the update, when a log is sent on the logstash input, the fields were set and discarded from the message : 
* facility
* facility_label
* priority
* program
* severity
* severity_label

I'm using the following versions :

- Version: Logstash 5.0.1 - Plugin 3.1.1
- Operating System: CentOS7 with docker container
- Config File (if you have sensitive info, please remove it):
```
input {
    syslog {
        port => 514
        timezone => "Europe/Paris"
        type => "syslog"
    }
}
```

Example of event : 
```
<134>Nov 18 17:27:40 tqdbr001s default: data/data-nginx-private: 10.42.179.10 - - es.qlf-fpl-data-middle.svc.meshcore.net [18/Nov/2016:17:27:40 +0100] POST "/_xpack/monitoring/_bulk" "system_id=kibana&system_api_version=2&interval=10000ms" "HTTP/1.1" 200 27 0.419 "-" "-",data/data-nginx-private: 10.42.179.10 - - es.qlf-fpl-data-middle.svc.meshcore.net [18/Nov/2016:17:27:40 +0100] POST "/_xpack/monitoring/_bulk" "system_id=kibana&system_api_version=2&interval=10000ms" "HTTP/1.1" 200 27 0.419 "-" "-"
```

Is it a normal change or a regression ?

Regards,

**Comment by jordansissel** [comment]
Can you include a sample syslog message to test with?

**Comment by bcecchinato** [comment]
@jordansissel Just did.

**Comment by bcecchinato** [comment]
What's weird is that there has been no changes from the sources that sends the logs on the platform. I've done some digging, and it seems that logstash adds some extra-informations before the syslog data : 
```
{
  "_index": "logstash-failed-2016.11.18",
  "_type": "logs",
  "_id": "AVh4Q9NpVsG_MQi7dxom",
  "_score": null,
  "_source": {
    "@timestamp": "2016-11-18T16:27:40.138Z",
    "@version": "1",
    "client": "failed",
    "message": "2016-11-18T16:27:40.003Z 10.42.179.24 <134>Nov 18 17:27:40 tqdbr001s default: data/data-nginx-private: 10.42.179.10 - - es.qlf-fpl-data-middle.svc.meshcore.net [18/Nov/2016:17:27:40 +0100] POST \"/_xpack/monitoring/_bulk\" \"system_id=kibana&system_api_version=2&interval=10000ms\" \"HTTP/1.1\" 200 27 0.419 \"-\" \"-\",data/data-nginx-private: 10.42.179.10 - - es.qlf-fpl-data-middle.svc.meshcore.net [18/Nov/2016:17:27:40 +0100] POST \"/_xpack/monitoring/_bulk\" \"system_id=kibana&system_api_version=2&interval=10000ms\" \"HTTP/1.1\" 200 27 0.419 \"-\" \"-\"",
    "index_day": "2016.11.18",
    "tags": []
  },
  "fields": {
    "@timestamp": [
      1479486460138
    ]
  },
  "sort": [
    1479486460138
  ]
}
```

See in the document the `2016-11-18T16:27:40.003Z 10.42.179.24`, that has been added. More interesting, the _type should be syslog, but i have logs instead. Hope this helps.

**Comment by bcecchinato** [comment]
@jordansissel I think i've found out where the issue is. We are using a kafka broker, and the output codec has changed from `json` to `plain`. I've made a test using the `json` codec again, and the fields are there.

Sorry for the issue.

Regards,

**Comment by jordansissel** [comment]
I am glad you got things working :)
