### ISSUE TITLE
Windows test crashes

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-syslog#4]
From https://github.com/elasticsearch/logstash/issues/2487

The tests, at least on windows, do something that cause rspec to crash out early before even running tests.

**Comment by jsvd** [comment]
Encoding problem again!!! https://github.com/logstash-plugins/logstash-input-syslog/blob/master/lib/logstash/inputs/syslog.rb#L187

**Comment by jsvd** [comment]
also #3 shows up during a failed run, fix in #5
