### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by tieungao88** [logstash-plugins/logstash-input-syslog#45]
Hi, I am installing plugin but I recived problem:
bin/logstash-plugin install --no-verify
Installing...
LoadError: no such file to load -- fileutils
  require at org/jruby/RubyKernel.java:944
    <top> at uri:classloader:/maven/tools/dsl.rb:1
  require at org/jruby/RubyKernel.java:944
    <top> at classpath:/parser.rb:1
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core (5.6.5), and Bundler cannot continue.

- Version Logstash: 5.6.5
- Operating System: centos 7
- Jruby: jruby 9.1.14.0 (2.3.3) 2017-11-08 2176f24 Java HotSpot(TM) 64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +jit [linux-x86_64]

Please help me resolve.

Thanks.

**Comment by kares** [comment]
hopefully, this got resoled since :crossed_fingers: for next time please try asking for support on the [forum](https://discuss.elastic.co/c/logstash)
